# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/teknic_motor_controller

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/teknic_motor_controller

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/teknic_motor_controller/CMakeFiles /home/pi/teknic_motor_controller/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/teknic_motor_controller/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LibMotors

# Build rule for target.
LibMotors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LibMotors
.PHONY : LibMotors

# fast build rule for target.
LibMotors/fast:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/build
.PHONY : LibMotors/fast

#=============================================================================
# Target rules for targets named Homing_Test

# Build rule for target.
Homing_Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Homing_Test
.PHONY : Homing_Test

# fast build rule for target.
Homing_Test/fast:
	$(MAKE) -f CMakeFiles/Homing_Test.dir/build.make CMakeFiles/Homing_Test.dir/build
.PHONY : Homing_Test/fast

#=============================================================================
# Target rules for targets named Motor_Test

# Build rule for target.
Motor_Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Motor_Test
.PHONY : Motor_Test

# fast build rule for target.
Motor_Test/fast:
	$(MAKE) -f CMakeFiles/Motor_Test.dir/build.make CMakeFiles/Motor_Test.dir/build
.PHONY : Motor_Test/fast

#=============================================================================
# Target rules for targets named LibINI

# Build rule for target.
LibINI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LibINI
.PHONY : LibINI

# fast build rule for target.
LibINI/fast:
	$(MAKE) -f CMakeFiles/LibINI.dir/build.make CMakeFiles/LibINI.dir/build
.PHONY : LibINI/fast

#=============================================================================
# Target rules for targets named LibLinuxOS

# Build rule for target.
LibLinuxOS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LibLinuxOS
.PHONY : LibLinuxOS

# fast build rule for target.
LibLinuxOS/fast:
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/build
.PHONY : LibLinuxOS/fast

#=============================================================================
# Target rules for targets named LibXML

# Build rule for target.
LibXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LibXML
.PHONY : LibXML

# fast build rule for target.
LibXML/fast:
	$(MAKE) -f CMakeFiles/LibXML.dir/build.make CMakeFiles/LibXML.dir/build
.PHONY : LibXML/fast

#=============================================================================
# Target rules for targets named sFoundation

# Build rule for target.
sFoundation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sFoundation
.PHONY : sFoundation

# fast build rule for target.
sFoundation/fast:
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/build
.PHONY : sFoundation/fast

src/LibINI/src/dictionary.o: src/LibINI/src/dictionary.cpp.o

.PHONY : src/LibINI/src/dictionary.o

# target to build an object file
src/LibINI/src/dictionary.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibINI/src/dictionary.cpp.o
	$(MAKE) -f CMakeFiles/LibINI.dir/build.make CMakeFiles/LibINI.dir/src/LibINI/src/dictionary.cpp.o
.PHONY : src/LibINI/src/dictionary.cpp.o

src/LibINI/src/dictionary.i: src/LibINI/src/dictionary.cpp.i

.PHONY : src/LibINI/src/dictionary.i

# target to preprocess a source file
src/LibINI/src/dictionary.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibINI/src/dictionary.cpp.i
	$(MAKE) -f CMakeFiles/LibINI.dir/build.make CMakeFiles/LibINI.dir/src/LibINI/src/dictionary.cpp.i
.PHONY : src/LibINI/src/dictionary.cpp.i

src/LibINI/src/dictionary.s: src/LibINI/src/dictionary.cpp.s

.PHONY : src/LibINI/src/dictionary.s

# target to generate assembly for a file
src/LibINI/src/dictionary.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibINI/src/dictionary.cpp.s
	$(MAKE) -f CMakeFiles/LibINI.dir/build.make CMakeFiles/LibINI.dir/src/LibINI/src/dictionary.cpp.s
.PHONY : src/LibINI/src/dictionary.cpp.s

src/LibINI/src/iniparser.o: src/LibINI/src/iniparser.cpp.o

.PHONY : src/LibINI/src/iniparser.o

# target to build an object file
src/LibINI/src/iniparser.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibINI/src/iniparser.cpp.o
	$(MAKE) -f CMakeFiles/LibINI.dir/build.make CMakeFiles/LibINI.dir/src/LibINI/src/iniparser.cpp.o
.PHONY : src/LibINI/src/iniparser.cpp.o

src/LibINI/src/iniparser.i: src/LibINI/src/iniparser.cpp.i

.PHONY : src/LibINI/src/iniparser.i

# target to preprocess a source file
src/LibINI/src/iniparser.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibINI/src/iniparser.cpp.i
	$(MAKE) -f CMakeFiles/LibINI.dir/build.make CMakeFiles/LibINI.dir/src/LibINI/src/iniparser.cpp.i
.PHONY : src/LibINI/src/iniparser.cpp.i

src/LibINI/src/iniparser.s: src/LibINI/src/iniparser.cpp.s

.PHONY : src/LibINI/src/iniparser.s

# target to generate assembly for a file
src/LibINI/src/iniparser.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibINI/src/iniparser.cpp.s
	$(MAKE) -f CMakeFiles/LibINI.dir/build.make CMakeFiles/LibINI.dir/src/LibINI/src/iniparser.cpp.s
.PHONY : src/LibINI/src/iniparser.cpp.s

src/LibLinuxOS/src/tekEventsLinux.o: src/LibLinuxOS/src/tekEventsLinux.cpp.o

.PHONY : src/LibLinuxOS/src/tekEventsLinux.o

# target to build an object file
src/LibLinuxOS/src/tekEventsLinux.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/tekEventsLinux.cpp.o
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/tekEventsLinux.cpp.o
.PHONY : src/LibLinuxOS/src/tekEventsLinux.cpp.o

src/LibLinuxOS/src/tekEventsLinux.i: src/LibLinuxOS/src/tekEventsLinux.cpp.i

.PHONY : src/LibLinuxOS/src/tekEventsLinux.i

# target to preprocess a source file
src/LibLinuxOS/src/tekEventsLinux.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/tekEventsLinux.cpp.i
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/tekEventsLinux.cpp.i
.PHONY : src/LibLinuxOS/src/tekEventsLinux.cpp.i

src/LibLinuxOS/src/tekEventsLinux.s: src/LibLinuxOS/src/tekEventsLinux.cpp.s

.PHONY : src/LibLinuxOS/src/tekEventsLinux.s

# target to generate assembly for a file
src/LibLinuxOS/src/tekEventsLinux.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/tekEventsLinux.cpp.s
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/tekEventsLinux.cpp.s
.PHONY : src/LibLinuxOS/src/tekEventsLinux.cpp.s

src/LibLinuxOS/src/tekThreadsLinux.o: src/LibLinuxOS/src/tekThreadsLinux.cpp.o

.PHONY : src/LibLinuxOS/src/tekThreadsLinux.o

# target to build an object file
src/LibLinuxOS/src/tekThreadsLinux.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/tekThreadsLinux.cpp.o
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/tekThreadsLinux.cpp.o
.PHONY : src/LibLinuxOS/src/tekThreadsLinux.cpp.o

src/LibLinuxOS/src/tekThreadsLinux.i: src/LibLinuxOS/src/tekThreadsLinux.cpp.i

.PHONY : src/LibLinuxOS/src/tekThreadsLinux.i

# target to preprocess a source file
src/LibLinuxOS/src/tekThreadsLinux.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/tekThreadsLinux.cpp.i
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/tekThreadsLinux.cpp.i
.PHONY : src/LibLinuxOS/src/tekThreadsLinux.cpp.i

src/LibLinuxOS/src/tekThreadsLinux.s: src/LibLinuxOS/src/tekThreadsLinux.cpp.s

.PHONY : src/LibLinuxOS/src/tekThreadsLinux.s

# target to generate assembly for a file
src/LibLinuxOS/src/tekThreadsLinux.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/tekThreadsLinux.cpp.s
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/tekThreadsLinux.cpp.s
.PHONY : src/LibLinuxOS/src/tekThreadsLinux.cpp.s

src/LibLinuxOS/src/version.o: src/LibLinuxOS/src/version.cpp.o

.PHONY : src/LibLinuxOS/src/version.o

# target to build an object file
src/LibLinuxOS/src/version.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/version.cpp.o
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/version.cpp.o
.PHONY : src/LibLinuxOS/src/version.cpp.o

src/LibLinuxOS/src/version.i: src/LibLinuxOS/src/version.cpp.i

.PHONY : src/LibLinuxOS/src/version.i

# target to preprocess a source file
src/LibLinuxOS/src/version.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/version.cpp.i
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/version.cpp.i
.PHONY : src/LibLinuxOS/src/version.cpp.i

src/LibLinuxOS/src/version.s: src/LibLinuxOS/src/version.cpp.s

.PHONY : src/LibLinuxOS/src/version.s

# target to generate assembly for a file
src/LibLinuxOS/src/version.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibLinuxOS/src/version.cpp.s
	$(MAKE) -f CMakeFiles/LibLinuxOS.dir/build.make CMakeFiles/LibLinuxOS.dir/src/LibLinuxOS/src/version.cpp.s
.PHONY : src/LibLinuxOS/src/version.cpp.s

src/LibMotors/src/clearPathMotors.o: src/LibMotors/src/clearPathMotors.cpp.o

.PHONY : src/LibMotors/src/clearPathMotors.o

# target to build an object file
src/LibMotors/src/clearPathMotors.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibMotors/src/clearPathMotors.cpp.o
.PHONY : src/LibMotors/src/clearPathMotors.cpp.o

src/LibMotors/src/clearPathMotors.i: src/LibMotors/src/clearPathMotors.cpp.i

.PHONY : src/LibMotors/src/clearPathMotors.i

# target to preprocess a source file
src/LibMotors/src/clearPathMotors.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibMotors/src/clearPathMotors.cpp.i
.PHONY : src/LibMotors/src/clearPathMotors.cpp.i

src/LibMotors/src/clearPathMotors.s: src/LibMotors/src/clearPathMotors.cpp.s

.PHONY : src/LibMotors/src/clearPathMotors.s

# target to generate assembly for a file
src/LibMotors/src/clearPathMotors.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibMotors/src/clearPathMotors.cpp.s
.PHONY : src/LibMotors/src/clearPathMotors.cpp.s

src/LibMotors/src/motors.o: src/LibMotors/src/motors.cpp.o

.PHONY : src/LibMotors/src/motors.o

# target to build an object file
src/LibMotors/src/motors.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibMotors/src/motors.cpp.o
.PHONY : src/LibMotors/src/motors.cpp.o

src/LibMotors/src/motors.i: src/LibMotors/src/motors.cpp.i

.PHONY : src/LibMotors/src/motors.i

# target to preprocess a source file
src/LibMotors/src/motors.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibMotors/src/motors.cpp.i
.PHONY : src/LibMotors/src/motors.cpp.i

src/LibMotors/src/motors.s: src/LibMotors/src/motors.cpp.s

.PHONY : src/LibMotors/src/motors.s

# target to generate assembly for a file
src/LibMotors/src/motors.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibMotors/src/motors.cpp.s
.PHONY : src/LibMotors/src/motors.cpp.s

src/LibXML/src/ErrCodeStr.o: src/LibXML/src/ErrCodeStr.cpp.o

.PHONY : src/LibXML/src/ErrCodeStr.o

# target to build an object file
src/LibXML/src/ErrCodeStr.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibXML/src/ErrCodeStr.cpp.o
	$(MAKE) -f CMakeFiles/LibXML.dir/build.make CMakeFiles/LibXML.dir/src/LibXML/src/ErrCodeStr.cpp.o
.PHONY : src/LibXML/src/ErrCodeStr.cpp.o

src/LibXML/src/ErrCodeStr.i: src/LibXML/src/ErrCodeStr.cpp.i

.PHONY : src/LibXML/src/ErrCodeStr.i

# target to preprocess a source file
src/LibXML/src/ErrCodeStr.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibXML/src/ErrCodeStr.cpp.i
	$(MAKE) -f CMakeFiles/LibXML.dir/build.make CMakeFiles/LibXML.dir/src/LibXML/src/ErrCodeStr.cpp.i
.PHONY : src/LibXML/src/ErrCodeStr.cpp.i

src/LibXML/src/ErrCodeStr.s: src/LibXML/src/ErrCodeStr.cpp.s

.PHONY : src/LibXML/src/ErrCodeStr.s

# target to generate assembly for a file
src/LibXML/src/ErrCodeStr.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibXML/src/ErrCodeStr.cpp.s
	$(MAKE) -f CMakeFiles/LibXML.dir/build.make CMakeFiles/LibXML.dir/src/LibXML/src/ErrCodeStr.cpp.s
.PHONY : src/LibXML/src/ErrCodeStr.cpp.s

src/LibXML/src/pugixml.o: src/LibXML/src/pugixml.cpp.o

.PHONY : src/LibXML/src/pugixml.o

# target to build an object file
src/LibXML/src/pugixml.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibXML/src/pugixml.cpp.o
	$(MAKE) -f CMakeFiles/LibXML.dir/build.make CMakeFiles/LibXML.dir/src/LibXML/src/pugixml.cpp.o
.PHONY : src/LibXML/src/pugixml.cpp.o

src/LibXML/src/pugixml.i: src/LibXML/src/pugixml.cpp.i

.PHONY : src/LibXML/src/pugixml.i

# target to preprocess a source file
src/LibXML/src/pugixml.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibXML/src/pugixml.cpp.i
	$(MAKE) -f CMakeFiles/LibXML.dir/build.make CMakeFiles/LibXML.dir/src/LibXML/src/pugixml.cpp.i
.PHONY : src/LibXML/src/pugixml.cpp.i

src/LibXML/src/pugixml.s: src/LibXML/src/pugixml.cpp.s

.PHONY : src/LibXML/src/pugixml.s

# target to generate assembly for a file
src/LibXML/src/pugixml.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/LibXML/src/pugixml.cpp.s
	$(MAKE) -f CMakeFiles/LibXML.dir/build.make CMakeFiles/LibXML.dir/src/LibXML/src/pugixml.cpp.s
.PHONY : src/LibXML/src/pugixml.cpp.s

src/motor_control/homing_test.o: src/motor_control/homing_test.cpp.o

.PHONY : src/motor_control/homing_test.o

# target to build an object file
src/motor_control/homing_test.cpp.o:
	$(MAKE) -f CMakeFiles/Homing_Test.dir/build.make CMakeFiles/Homing_Test.dir/src/motor_control/homing_test.cpp.o
.PHONY : src/motor_control/homing_test.cpp.o

src/motor_control/homing_test.i: src/motor_control/homing_test.cpp.i

.PHONY : src/motor_control/homing_test.i

# target to preprocess a source file
src/motor_control/homing_test.cpp.i:
	$(MAKE) -f CMakeFiles/Homing_Test.dir/build.make CMakeFiles/Homing_Test.dir/src/motor_control/homing_test.cpp.i
.PHONY : src/motor_control/homing_test.cpp.i

src/motor_control/homing_test.s: src/motor_control/homing_test.cpp.s

.PHONY : src/motor_control/homing_test.s

# target to generate assembly for a file
src/motor_control/homing_test.cpp.s:
	$(MAKE) -f CMakeFiles/Homing_Test.dir/build.make CMakeFiles/Homing_Test.dir/src/motor_control/homing_test.cpp.s
.PHONY : src/motor_control/homing_test.cpp.s

src/motor_control/motor_test.o: src/motor_control/motor_test.cpp.o

.PHONY : src/motor_control/motor_test.o

# target to build an object file
src/motor_control/motor_test.cpp.o:
	$(MAKE) -f CMakeFiles/Motor_Test.dir/build.make CMakeFiles/Motor_Test.dir/src/motor_control/motor_test.cpp.o
.PHONY : src/motor_control/motor_test.cpp.o

src/motor_control/motor_test.i: src/motor_control/motor_test.cpp.i

.PHONY : src/motor_control/motor_test.i

# target to preprocess a source file
src/motor_control/motor_test.cpp.i:
	$(MAKE) -f CMakeFiles/Motor_Test.dir/build.make CMakeFiles/Motor_Test.dir/src/motor_control/motor_test.cpp.i
.PHONY : src/motor_control/motor_test.cpp.i

src/motor_control/motor_test.s: src/motor_control/motor_test.cpp.s

.PHONY : src/motor_control/motor_test.s

# target to generate assembly for a file
src/motor_control/motor_test.cpp.s:
	$(MAKE) -f CMakeFiles/Motor_Test.dir/build.make CMakeFiles/Motor_Test.dir/src/motor_control/motor_test.cpp.s
.PHONY : src/motor_control/motor_test.cpp.s

src/sFoundation/src-linux/SerialLinux.o: src/sFoundation/src-linux/SerialLinux.cpp.o

.PHONY : src/sFoundation/src-linux/SerialLinux.o

# target to build an object file
src/sFoundation/src-linux/SerialLinux.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src-linux/SerialLinux.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src-linux/SerialLinux.cpp.o
.PHONY : src/sFoundation/src-linux/SerialLinux.cpp.o

src/sFoundation/src-linux/SerialLinux.i: src/sFoundation/src-linux/SerialLinux.cpp.i

.PHONY : src/sFoundation/src-linux/SerialLinux.i

# target to preprocess a source file
src/sFoundation/src-linux/SerialLinux.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src-linux/SerialLinux.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src-linux/SerialLinux.cpp.i
.PHONY : src/sFoundation/src-linux/SerialLinux.cpp.i

src/sFoundation/src-linux/SerialLinux.s: src/sFoundation/src-linux/SerialLinux.cpp.s

.PHONY : src/sFoundation/src-linux/SerialLinux.s

# target to generate assembly for a file
src/sFoundation/src-linux/SerialLinux.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src-linux/SerialLinux.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src-linux/SerialLinux.cpp.s
.PHONY : src/sFoundation/src-linux/SerialLinux.cpp.s

src/sFoundation/src-linux/lnkAccessLinux.o: src/sFoundation/src-linux/lnkAccessLinux.cpp.o

.PHONY : src/sFoundation/src-linux/lnkAccessLinux.o

# target to build an object file
src/sFoundation/src-linux/lnkAccessLinux.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src-linux/lnkAccessLinux.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src-linux/lnkAccessLinux.cpp.o
.PHONY : src/sFoundation/src-linux/lnkAccessLinux.cpp.o

src/sFoundation/src-linux/lnkAccessLinux.i: src/sFoundation/src-linux/lnkAccessLinux.cpp.i

.PHONY : src/sFoundation/src-linux/lnkAccessLinux.i

# target to preprocess a source file
src/sFoundation/src-linux/lnkAccessLinux.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src-linux/lnkAccessLinux.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src-linux/lnkAccessLinux.cpp.i
.PHONY : src/sFoundation/src-linux/lnkAccessLinux.cpp.i

src/sFoundation/src-linux/lnkAccessLinux.s: src/sFoundation/src-linux/lnkAccessLinux.cpp.s

.PHONY : src/sFoundation/src-linux/lnkAccessLinux.s

# target to generate assembly for a file
src/sFoundation/src-linux/lnkAccessLinux.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src-linux/lnkAccessLinux.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src-linux/lnkAccessLinux.cpp.s
.PHONY : src/sFoundation/src-linux/lnkAccessLinux.cpp.s

src/sFoundation/src/SerialEx.o: src/sFoundation/src/SerialEx.cpp.o

.PHONY : src/sFoundation/src/SerialEx.o

# target to build an object file
src/sFoundation/src/SerialEx.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/SerialEx.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/SerialEx.cpp.o
.PHONY : src/sFoundation/src/SerialEx.cpp.o

src/sFoundation/src/SerialEx.i: src/sFoundation/src/SerialEx.cpp.i

.PHONY : src/sFoundation/src/SerialEx.i

# target to preprocess a source file
src/sFoundation/src/SerialEx.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/SerialEx.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/SerialEx.cpp.i
.PHONY : src/sFoundation/src/SerialEx.cpp.i

src/sFoundation/src/SerialEx.s: src/sFoundation/src/SerialEx.cpp.s

.PHONY : src/sFoundation/src/SerialEx.s

# target to generate assembly for a file
src/sFoundation/src/SerialEx.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/SerialEx.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/SerialEx.cpp.s
.PHONY : src/sFoundation/src/SerialEx.cpp.s

src/sFoundation/src/converterLib.o: src/sFoundation/src/converterLib.cpp.o

.PHONY : src/sFoundation/src/converterLib.o

# target to build an object file
src/sFoundation/src/converterLib.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/converterLib.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/converterLib.cpp.o
.PHONY : src/sFoundation/src/converterLib.cpp.o

src/sFoundation/src/converterLib.i: src/sFoundation/src/converterLib.cpp.i

.PHONY : src/sFoundation/src/converterLib.i

# target to preprocess a source file
src/sFoundation/src/converterLib.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/converterLib.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/converterLib.cpp.i
.PHONY : src/sFoundation/src/converterLib.cpp.i

src/sFoundation/src/converterLib.s: src/sFoundation/src/converterLib.cpp.s

.PHONY : src/sFoundation/src/converterLib.s

# target to generate assembly for a file
src/sFoundation/src/converterLib.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/converterLib.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/converterLib.cpp.s
.PHONY : src/sFoundation/src/converterLib.cpp.s

src/sFoundation/src/cpmAPI.o: src/sFoundation/src/cpmAPI.cpp.o

.PHONY : src/sFoundation/src/cpmAPI.o

# target to build an object file
src/sFoundation/src/cpmAPI.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/cpmAPI.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/cpmAPI.cpp.o
.PHONY : src/sFoundation/src/cpmAPI.cpp.o

src/sFoundation/src/cpmAPI.i: src/sFoundation/src/cpmAPI.cpp.i

.PHONY : src/sFoundation/src/cpmAPI.i

# target to preprocess a source file
src/sFoundation/src/cpmAPI.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/cpmAPI.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/cpmAPI.cpp.i
.PHONY : src/sFoundation/src/cpmAPI.cpp.i

src/sFoundation/src/cpmAPI.s: src/sFoundation/src/cpmAPI.cpp.s

.PHONY : src/sFoundation/src/cpmAPI.s

# target to generate assembly for a file
src/sFoundation/src/cpmAPI.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/cpmAPI.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/cpmAPI.cpp.s
.PHONY : src/sFoundation/src/cpmAPI.cpp.s

src/sFoundation/src/cpmClassImpl.o: src/sFoundation/src/cpmClassImpl.cpp.o

.PHONY : src/sFoundation/src/cpmClassImpl.o

# target to build an object file
src/sFoundation/src/cpmClassImpl.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/cpmClassImpl.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/cpmClassImpl.cpp.o
.PHONY : src/sFoundation/src/cpmClassImpl.cpp.o

src/sFoundation/src/cpmClassImpl.i: src/sFoundation/src/cpmClassImpl.cpp.i

.PHONY : src/sFoundation/src/cpmClassImpl.i

# target to preprocess a source file
src/sFoundation/src/cpmClassImpl.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/cpmClassImpl.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/cpmClassImpl.cpp.i
.PHONY : src/sFoundation/src/cpmClassImpl.cpp.i

src/sFoundation/src/cpmClassImpl.s: src/sFoundation/src/cpmClassImpl.cpp.s

.PHONY : src/sFoundation/src/cpmClassImpl.s

# target to generate assembly for a file
src/sFoundation/src/cpmClassImpl.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/cpmClassImpl.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/cpmClassImpl.cpp.s
.PHONY : src/sFoundation/src/cpmClassImpl.cpp.s

src/sFoundation/src/iscAPI.o: src/sFoundation/src/iscAPI.cpp.o

.PHONY : src/sFoundation/src/iscAPI.o

# target to build an object file
src/sFoundation/src/iscAPI.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/iscAPI.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/iscAPI.cpp.o
.PHONY : src/sFoundation/src/iscAPI.cpp.o

src/sFoundation/src/iscAPI.i: src/sFoundation/src/iscAPI.cpp.i

.PHONY : src/sFoundation/src/iscAPI.i

# target to preprocess a source file
src/sFoundation/src/iscAPI.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/iscAPI.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/iscAPI.cpp.i
.PHONY : src/sFoundation/src/iscAPI.cpp.i

src/sFoundation/src/iscAPI.s: src/sFoundation/src/iscAPI.cpp.s

.PHONY : src/sFoundation/src/iscAPI.s

# target to generate assembly for a file
src/sFoundation/src/iscAPI.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/iscAPI.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/iscAPI.cpp.s
.PHONY : src/sFoundation/src/iscAPI.cpp.s

src/sFoundation/src/lnkAccessCommon.o: src/sFoundation/src/lnkAccessCommon.cpp.o

.PHONY : src/sFoundation/src/lnkAccessCommon.o

# target to build an object file
src/sFoundation/src/lnkAccessCommon.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/lnkAccessCommon.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/lnkAccessCommon.cpp.o
.PHONY : src/sFoundation/src/lnkAccessCommon.cpp.o

src/sFoundation/src/lnkAccessCommon.i: src/sFoundation/src/lnkAccessCommon.cpp.i

.PHONY : src/sFoundation/src/lnkAccessCommon.i

# target to preprocess a source file
src/sFoundation/src/lnkAccessCommon.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/lnkAccessCommon.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/lnkAccessCommon.cpp.i
.PHONY : src/sFoundation/src/lnkAccessCommon.cpp.i

src/sFoundation/src/lnkAccessCommon.s: src/sFoundation/src/lnkAccessCommon.cpp.s

.PHONY : src/sFoundation/src/lnkAccessCommon.s

# target to generate assembly for a file
src/sFoundation/src/lnkAccessCommon.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/lnkAccessCommon.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/lnkAccessCommon.cpp.s
.PHONY : src/sFoundation/src/lnkAccessCommon.cpp.s

src/sFoundation/src/meridianNet.o: src/sFoundation/src/meridianNet.cpp.o

.PHONY : src/sFoundation/src/meridianNet.o

# target to build an object file
src/sFoundation/src/meridianNet.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/meridianNet.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/meridianNet.cpp.o
.PHONY : src/sFoundation/src/meridianNet.cpp.o

src/sFoundation/src/meridianNet.i: src/sFoundation/src/meridianNet.cpp.i

.PHONY : src/sFoundation/src/meridianNet.i

# target to preprocess a source file
src/sFoundation/src/meridianNet.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/meridianNet.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/meridianNet.cpp.i
.PHONY : src/sFoundation/src/meridianNet.cpp.i

src/sFoundation/src/meridianNet.s: src/sFoundation/src/meridianNet.cpp.s

.PHONY : src/sFoundation/src/meridianNet.s

# target to generate assembly for a file
src/sFoundation/src/meridianNet.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/meridianNet.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/meridianNet.cpp.s
.PHONY : src/sFoundation/src/meridianNet.cpp.s

src/sFoundation/src/netCmdAPI.o: src/sFoundation/src/netCmdAPI.cpp.o

.PHONY : src/sFoundation/src/netCmdAPI.o

# target to build an object file
src/sFoundation/src/netCmdAPI.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/netCmdAPI.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/netCmdAPI.cpp.o
.PHONY : src/sFoundation/src/netCmdAPI.cpp.o

src/sFoundation/src/netCmdAPI.i: src/sFoundation/src/netCmdAPI.cpp.i

.PHONY : src/sFoundation/src/netCmdAPI.i

# target to preprocess a source file
src/sFoundation/src/netCmdAPI.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/netCmdAPI.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/netCmdAPI.cpp.i
.PHONY : src/sFoundation/src/netCmdAPI.cpp.i

src/sFoundation/src/netCmdAPI.s: src/sFoundation/src/netCmdAPI.cpp.s

.PHONY : src/sFoundation/src/netCmdAPI.s

# target to generate assembly for a file
src/sFoundation/src/netCmdAPI.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/netCmdAPI.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/netCmdAPI.cpp.s
.PHONY : src/sFoundation/src/netCmdAPI.cpp.s

src/sFoundation/src/netCoreFmt.o: src/sFoundation/src/netCoreFmt.cpp.o

.PHONY : src/sFoundation/src/netCoreFmt.o

# target to build an object file
src/sFoundation/src/netCoreFmt.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/netCoreFmt.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/netCoreFmt.cpp.o
.PHONY : src/sFoundation/src/netCoreFmt.cpp.o

src/sFoundation/src/netCoreFmt.i: src/sFoundation/src/netCoreFmt.cpp.i

.PHONY : src/sFoundation/src/netCoreFmt.i

# target to preprocess a source file
src/sFoundation/src/netCoreFmt.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/netCoreFmt.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/netCoreFmt.cpp.i
.PHONY : src/sFoundation/src/netCoreFmt.cpp.i

src/sFoundation/src/netCoreFmt.s: src/sFoundation/src/netCoreFmt.cpp.s

.PHONY : src/sFoundation/src/netCoreFmt.s

# target to generate assembly for a file
src/sFoundation/src/netCoreFmt.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/netCoreFmt.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/netCoreFmt.cpp.s
.PHONY : src/sFoundation/src/netCoreFmt.cpp.s

src/sFoundation/src/sysClassImpl.o: src/sFoundation/src/sysClassImpl.cpp.o

.PHONY : src/sFoundation/src/sysClassImpl.o

# target to build an object file
src/sFoundation/src/sysClassImpl.cpp.o:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/sysClassImpl.cpp.o
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/sysClassImpl.cpp.o
.PHONY : src/sFoundation/src/sysClassImpl.cpp.o

src/sFoundation/src/sysClassImpl.i: src/sFoundation/src/sysClassImpl.cpp.i

.PHONY : src/sFoundation/src/sysClassImpl.i

# target to preprocess a source file
src/sFoundation/src/sysClassImpl.cpp.i:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/sysClassImpl.cpp.i
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/sysClassImpl.cpp.i
.PHONY : src/sFoundation/src/sysClassImpl.cpp.i

src/sFoundation/src/sysClassImpl.s: src/sFoundation/src/sysClassImpl.cpp.s

.PHONY : src/sFoundation/src/sysClassImpl.s

# target to generate assembly for a file
src/sFoundation/src/sysClassImpl.cpp.s:
	$(MAKE) -f CMakeFiles/LibMotors.dir/build.make CMakeFiles/LibMotors.dir/src/sFoundation/src/sysClassImpl.cpp.s
	$(MAKE) -f CMakeFiles/sFoundation.dir/build.make CMakeFiles/sFoundation.dir/src/sFoundation/src/sysClassImpl.cpp.s
.PHONY : src/sFoundation/src/sysClassImpl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... LibMotors"
	@echo "... Homing_Test"
	@echo "... edit_cache"
	@echo "... Motor_Test"
	@echo "... LibINI"
	@echo "... LibLinuxOS"
	@echo "... LibXML"
	@echo "... sFoundation"
	@echo "... src/LibINI/src/dictionary.o"
	@echo "... src/LibINI/src/dictionary.i"
	@echo "... src/LibINI/src/dictionary.s"
	@echo "... src/LibINI/src/iniparser.o"
	@echo "... src/LibINI/src/iniparser.i"
	@echo "... src/LibINI/src/iniparser.s"
	@echo "... src/LibLinuxOS/src/tekEventsLinux.o"
	@echo "... src/LibLinuxOS/src/tekEventsLinux.i"
	@echo "... src/LibLinuxOS/src/tekEventsLinux.s"
	@echo "... src/LibLinuxOS/src/tekThreadsLinux.o"
	@echo "... src/LibLinuxOS/src/tekThreadsLinux.i"
	@echo "... src/LibLinuxOS/src/tekThreadsLinux.s"
	@echo "... src/LibLinuxOS/src/version.o"
	@echo "... src/LibLinuxOS/src/version.i"
	@echo "... src/LibLinuxOS/src/version.s"
	@echo "... src/LibMotors/src/clearPathMotors.o"
	@echo "... src/LibMotors/src/clearPathMotors.i"
	@echo "... src/LibMotors/src/clearPathMotors.s"
	@echo "... src/LibMotors/src/motors.o"
	@echo "... src/LibMotors/src/motors.i"
	@echo "... src/LibMotors/src/motors.s"
	@echo "... src/LibXML/src/ErrCodeStr.o"
	@echo "... src/LibXML/src/ErrCodeStr.i"
	@echo "... src/LibXML/src/ErrCodeStr.s"
	@echo "... src/LibXML/src/pugixml.o"
	@echo "... src/LibXML/src/pugixml.i"
	@echo "... src/LibXML/src/pugixml.s"
	@echo "... src/motor_control/homing_test.o"
	@echo "... src/motor_control/homing_test.i"
	@echo "... src/motor_control/homing_test.s"
	@echo "... src/motor_control/motor_test.o"
	@echo "... src/motor_control/motor_test.i"
	@echo "... src/motor_control/motor_test.s"
	@echo "... src/sFoundation/src-linux/SerialLinux.o"
	@echo "... src/sFoundation/src-linux/SerialLinux.i"
	@echo "... src/sFoundation/src-linux/SerialLinux.s"
	@echo "... src/sFoundation/src-linux/lnkAccessLinux.o"
	@echo "... src/sFoundation/src-linux/lnkAccessLinux.i"
	@echo "... src/sFoundation/src-linux/lnkAccessLinux.s"
	@echo "... src/sFoundation/src/SerialEx.o"
	@echo "... src/sFoundation/src/SerialEx.i"
	@echo "... src/sFoundation/src/SerialEx.s"
	@echo "... src/sFoundation/src/converterLib.o"
	@echo "... src/sFoundation/src/converterLib.i"
	@echo "... src/sFoundation/src/converterLib.s"
	@echo "... src/sFoundation/src/cpmAPI.o"
	@echo "... src/sFoundation/src/cpmAPI.i"
	@echo "... src/sFoundation/src/cpmAPI.s"
	@echo "... src/sFoundation/src/cpmClassImpl.o"
	@echo "... src/sFoundation/src/cpmClassImpl.i"
	@echo "... src/sFoundation/src/cpmClassImpl.s"
	@echo "... src/sFoundation/src/iscAPI.o"
	@echo "... src/sFoundation/src/iscAPI.i"
	@echo "... src/sFoundation/src/iscAPI.s"
	@echo "... src/sFoundation/src/lnkAccessCommon.o"
	@echo "... src/sFoundation/src/lnkAccessCommon.i"
	@echo "... src/sFoundation/src/lnkAccessCommon.s"
	@echo "... src/sFoundation/src/meridianNet.o"
	@echo "... src/sFoundation/src/meridianNet.i"
	@echo "... src/sFoundation/src/meridianNet.s"
	@echo "... src/sFoundation/src/netCmdAPI.o"
	@echo "... src/sFoundation/src/netCmdAPI.i"
	@echo "... src/sFoundation/src/netCmdAPI.s"
	@echo "... src/sFoundation/src/netCoreFmt.o"
	@echo "... src/sFoundation/src/netCoreFmt.i"
	@echo "... src/sFoundation/src/netCoreFmt.s"
	@echo "... src/sFoundation/src/sysClassImpl.o"
	@echo "... src/sFoundation/src/sysClassImpl.i"
	@echo "... src/sFoundation/src/sysClassImpl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

